services:
  web:
    build: .
    volumes:
      - ./src:/app
      - ./modesl:/src/CASALIOY/models
    ports:
      - "8501:8501"
    shm_size: '16gb'
    privileged: true
    command: sleep infinity